In [1]:
import pandas as pd

In [4]:
x = pd.read_csv(r'https://github.com/chrisstrods/aflengine/raw/master/bench/matches.csv')

In [5]:
x.head()

,round,venue,date,day,time,crowd,hteam,hteam_q1,hteam_q2,hteam_q3,...,hteam_et,ateam_et,season,matchid,homeodds,homeline,awayodds,awayline,hscore,ascore
0,1,Moorabbin Oval,1-Apr-1972,Sat,2:10,21373.0,St Kilda,2.1.13,11.6.72,13.10.88,...,NaN,NaN,1972,197201NORSTK,NaN,NaN,NaN,NaN,134,76
1,1,Princes Park,1-Apr-1972,Sat,2:10,33601.0,Carlton,2.4.16,5.9.39,7.11.53,...,NaN,NaN,1972,197201CARFIT,NaN,NaN,NaN,NaN,81,70
2,1,Glenferrie Oval,1-Apr-1972,Sat,2:10,21513.0,Hawthorn,4.3.27,9.4.58,10.10.70,...,NaN,NaN,1972,197201HAWMEL,NaN,NaN,NaN,NaN,104,75
3,1,Western Oval,1-Apr-1978,Sat,2:10,20420.0,Footscray,2.4.16,9.7.61,10.11.71,...,NaN,NaN,1978,197801FOTNOR,NaN,NaN,NaN,NaN,80,149
4,1,Princes Park,1-Apr-1978,Sat,2:10,11986.0,Hawthorn,3.6.24,7.11.53,14.11.95,...,NaN,NaN,1978,197801HAWMEL,NaN,NaN,NaN,NaN,147,68